import type { SanitizedHtml } from "@/lib/markdown"
import { cn } from "@/lib/utils"

type MarkdownContentProps = Readonly<{
  html: SanitizedHtml
}>

const markdownContentClassName = cn(
  "prose prose-neutral max-w-none scroll-smooth text-foreground dark:prose-invert",
  "prose-a:text-foreground prose-a:decoration-border prose-a:underline-offset-4",
  "prose-code:rounded-sm prose-code:bg-muted prose-code:px-1.5 prose-code:py-0.5 prose-code:font-mono prose-code:text-sm prose-code:text-foreground",
  "prose-h2:scroll-mt-14 prose-h3:scroll-mt-14 xl:prose-h2:scroll-mt-8 xl:prose-h3:scroll-mt-8",
  "prose-pre:overflow-x-auto prose-pre:rounded-md prose-pre:border prose-pre:border-border prose-pre:bg-muted prose-pre:text-foreground",
  "prose-table:block prose-table:max-w-full prose-table:overflow-x-auto",
  "[&_code[data-theme]_span]:text-[var(--shiki-light)] dark:[&_code[data-theme]_span]:text-[var(--shiki-dark)]",
)

export function MarkdownContent({ html }: MarkdownContentProps) {
  return (
    <div
      className={markdownContentClassName}
      // biome-ignore lint/security/noDangerouslySetInnerHtml: Markdown HTML is generated by unified with raw HTML disabled and rehype-sanitize enabled.
      dangerouslySetInnerHTML={{ __html: html }}
    />
  )
}
