import { PostDiagramRenderer } from "@/features/post-diagram/post-diagram-renderer"
import { prefixBasePath } from "@/lib/base-path"
import type { SanitizedHtml } from "@/lib/markdown"
import { cn } from "@/lib/utils"

type MarkdownContentProps = Readonly<{
  contentKey: string
  hasDiagram: boolean
  hasMath: boolean
  html: SanitizedHtml
}>

const DEFAULT_KATEX_CSS_PATH = "/katex/katex.min.css"

/**
 * GitHub Pages 서브경로(e.g. /repo/) 배포 환경을 지원하기 위해
 * 환경변수 NEXT_PUBLIC_BASE_PATH 가 지정된 경우 KaTeX 스타일시트 경로 앞에 접두사로 조합합니다.
 */
export function getKatexStylesheetUrl(): string {
  return prefixBasePath(DEFAULT_KATEX_CSS_PATH)
}

const markdownContentClassName = cn(
  "prose prose-neutral max-w-none text-foreground dark:prose-invert",
  "prose-a:text-foreground prose-a:decoration-border prose-a:underline-offset-4",
  "prose-code:rounded-sm prose-code:bg-muted prose-code:px-1.5 prose-code:py-0.5 prose-code:font-mono prose-code:text-sm prose-code:text-foreground",
  "prose-h2:scroll-mt-14 prose-h3:scroll-mt-14 xl:prose-h2:scroll-mt-8 xl:prose-h3:scroll-mt-8",
  "prose-pre:overflow-x-auto prose-pre:rounded-md prose-pre:border prose-pre:border-border prose-pre:bg-muted prose-pre:text-foreground",
  "[&_.table-wrapper]:max-w-full [&_.table-wrapper]:overflow-x-auto",
  "[&_.katex-display]:max-w-full [&_.katex-display]:overflow-x-auto [&_.katex-display]:overflow-y-hidden",
  "[&_pre.mermaid]:grid [&_pre.mermaid]:min-h-28 [&_pre.mermaid]:place-items-center [&_pre.mermaid]:whitespace-pre-wrap [&_pre.mermaid]:p-4",
  "[&_pre.mermaid_svg]:h-auto [&_pre.mermaid_svg]:max-w-full",
  "[&_pre.mermaid[data-diagram-state=error]]:place-items-start [&_pre.mermaid[data-diagram-state=error]]:border-destructive",
  "[&_code[data-theme]_span]:text-[var(--shiki-light)] dark:[&_code[data-theme]_span]:text-[var(--shiki-dark)]",
)

const MARKDOWN_CONTENT_ID = "post-markdown-content"

export function MarkdownContent({ contentKey, hasDiagram, hasMath, html }: MarkdownContentProps) {
  const markdownContentId = `${MARKDOWN_CONTENT_ID}-${contentKey}`

  return (
    <>
      {hasMath ? (
        <link href={getKatexStylesheetUrl()} precedence="default" rel="stylesheet" />
      ) : null}
      <div
        id={markdownContentId}
        className={markdownContentClassName}
        // biome-ignore lint/security/noDangerouslySetInnerHtml: Markdown HTML is generated by unified with raw HTML disabled and rehype-sanitize enabled.
        dangerouslySetInnerHTML={{ __html: html }}
      />
      {hasDiagram ? <PostDiagramRenderer containerId={markdownContentId} /> : null}
    </>
  )
}
